### ISSUE TITLE
bbs started by wwivd is not finding network1

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#870]
using the new wwivd setup.  I have NET_PROCESS = Y for all nodes, so when I log off, it tries to find network1 to process messages.

The result is it hangs indefinitely because of an infinite loop to run network1. 

```
Oct 09 12:37:47 vps40748.vps.ovh.ca wwivd[18902]: /bin/sh: 1: network1: not found
Oct 09 12:37:47 vps40748.vps.ovh.ca wwivd[18902]: /bin/sh: 1: network1: not found
Oct 09 12:37:47 vps40748.vps.ovh.ca wwivd[18902]: /bin/sh: 1: network1: not found
Oct 09 12:37:47 vps40748.vps.ovh.ca wwivd[18902]: /bin/sh: 1: network1: not found
```

etc

That means it's not in the right directory and can't find the binary.  That doesn't make sense though, because it had to be in the right directory to start bbs in the first place (i.e., it's using relative pathing to start bbs)

```
Invoking WWIV with command line:./bbs -XT -H6 -N2
```

so if it was in the right directory for bbs, why is it not in the right directory to run network1?  It might be because of dropped environment information because of the exec call.  We need to be able to verify current working directory before and after each call.

**Comment by granitepenguin** [comment]
Also, since this is being managed as a service now, all the logging is in /var/log/syslog, which is nice (i.e., no more crud spraying on the user's session at logout).

To replicate the issue, 
1. enable NET_PROCESS = Y
2. log on and email test message to another node
3. logout (/O)

At this point, the connection will appear to hang, and you should see a flood of network1: not found messages in syslog

**Comment by wwiv** [comment]
is this fixed now?

**Comment by granitepenguin** [comment]
I would say yes.  I'm not seeing any more issues with it

**Comment by granitepenguin** [comment]
Looks like this is still happening in 5.2.0.2192 ( not sure if it's a regression or not).
need to get better environmental logging so we can tell what's happening.

Possible cause... looking at the error message: 
`/bin/sh: 1: network1: not found`
on linux, if we are in the same directory as a binary, your current working directory is NOT in your path (this is a security feature in linux).  You need to either start with `./` or give a full path.

So it shouldn't be trying to run `network1`, it should be running `./network1`

**Comment by granitepenguin** [comment]
looks like 2195 is finding network1 ok now, but I noticed the following error

`
Oct 16 11:35:18 vps40748 wwivd[25084]: 2016-10-16 11:35:18,644 FATAL BBS Terminated by exception: basic_string::_S_construct null not valid
Oct 16 11:35:18 vps40748 wwivd[25084]: 2016-10-16 11:35:18,644 WARN  Aborting application. Reason: Fatal log at [/jenkins/workspace/wwiv/label/linux/bbs/bbs.cpp:112]
`

**Comment by wwiv** [comment]
ok, that fatal error is fixed
