### ISSUE TITLE
CentOS 7 compile warnings

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#976]
Just a list of warnings I found compiling on CentOS 7.

```bash
[  7%] Building CXX object core_test/CMakeFiles/core_tests.dir/crc32_test.cpp.o
In file included from /home/drock/git/wwiv/core_test/crc32_test.cpp:19:0:
/home/drock/git/wwiv/core_test/../deps/googletest-master/googletest/include/gtest/gtest.h: In instantiation of ‘testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = int; T2 = unsigned int]’:
/home/drock/git/wwiv/core_test/../deps/googletest-master/googletest/include/gtest/gtest.h:1421:64:   required from ‘static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = int; T2 = unsigned int; bool lhs_is_null_literal = false]’
/home/drock/git/wwiv/core_test/crc32_test.cpp:43:3:   required from here
/home/drock/git/wwiv/core_test/../deps/googletest-master/googletest/include/gtest/gtest.h:1392:11: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (lhs == rhs) {
           ^

[  8%] Building CXX object core_test/CMakeFiles/core_tests.dir/file_test.cpp.o
In file included from /home/drock/git/wwiv/core_test/file_test.cpp:20:0:
/home/drock/git/wwiv/core_test/../deps/googletest-master/googletest/include/gtest/gtest.h: In instantiation of ‘testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = long int]’:
/home/drock/git/wwiv/core_test/../deps/googletest-master/googletest/include/gtest/gtest.h:1421:64:   required from ‘static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = long int; bool lhs_is_null_literal = false]’
/home/drock/git/wwiv/core_test/file_test.cpp:371:3:   required from here
/home/drock/git/wwiv/core_test/../deps/googletest-master/googletest/include/gtest/gtest.h:1392:11: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (lhs == rhs) {
           ^

[ 10%] Building CXX object core_test/CMakeFiles/core_tests.dir/strings_test.cpp.o
In file included from /home/drock/git/wwiv/core_test/strings_test.cpp:19:0:
/home/drock/git/wwiv/core_test/../deps/googletest-master/googletest/include/gtest/gtest.h: In instantiation of ‘testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = int; T2 = long unsigned int]’:
/home/drock/git/wwiv/core_test/../deps/googletest-master/googletest/include/gtest/gtest.h:1421:64:   required from ‘static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = int; T2 = long unsigned int; bool lhs_is_null_literal = false’
/home/drock/git/wwiv/core_test/strings_test.cpp:385:3:   required from here
/home/drock/git/wwiv/core_test/../deps/googletest-master/googletest/include/gtest/gtest.h:1392:11: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (lhs == rhs) {
           ^

[ 16%] Building CXX object sdk/CMakeFiles/sdk.dir/msgapi/message_area_wwiv.cpp.o
In file included from /home/drock/git/wwiv/sdk/msgapi/message_area_wwiv.cpp:18:0:
/home/drock/git/wwiv/sdk/../sdk/msgapi/message_area_wwiv.h: In constructor ‘wwiv::sdk::msgapi::WWIVMessageAreaLastRead::WWIVMessageAreaLastRead(wwiv::sdk::msgapi::WWIVMessageApi*, int)’:
/home/drock/git/wwiv/sdk/../sdk/msgapi/message_area_wwiv.h:70:19: warning: ‘wwiv::sdk::msgapi::WWIVMessageAreaLastRead::wapi_’ will be initialized after [-Wreorder]
   WWIVMessageApi* wapi_;
                   ^
/home/drock/git/wwiv/sdk/../sdk/msgapi/message_area_wwiv.h:69:7: warning:   ‘int wwiv::sdk::msgapi::WWIVMessageAreaLastRead::message_area_number_’ [-Wreorder]
   int message_area_number_;
       ^
/home/drock/git/wwiv/sdk/msgapi/message_area_wwiv.cpp:97:1: warning:   when initialized here [-Wreorder]
 WWIVMessageAreaLastRead::WWIVMessageAreaLastRead(WWIVMessageApi* api, int message_area_number) 
 ^

[ 20%] Building CXX object sdk/CMakeFiles/sdk.dir/subxtr.cpp.o
In file included from /home/drock/git/wwiv/sdk/../bbs/vars.h:24:0,
                 from /home/drock/git/wwiv/sdk/subxtr.cpp:30:
/home/drock/git/wwiv/sdk/../bbs/conf.h: In constructor ‘conf_info_t::conf_info_t(std::vector<confrec>&, std::vector<userconfrec>&)’:
/home/drock/git/wwiv/sdk/../bbs/conf.h:88:29: warning: ‘conf_info_t::uc’ will be initialized after [-Wreorder]
   std::vector<userconfrec>& uc;
                             ^
/home/drock/git/wwiv/sdk/../bbs/conf.h:86:7: warning:   ‘int conf_info_t::num_confs’ [-Wreorder]
   int num_confs;
       ^
/home/drock/git/wwiv/sdk/../bbs/conf.h:83:3: warning:   when initialized here [-Wreorder]
   conf_info_t(std::vector<confrec>& c, std::vector<userconfrec>& u)
   ^

[ 60%] Building C object bbs/CMakeFiles/bbs_lib.dir/__/deps/my_basic-master/core/my_basic.c.o
/home/drock/git/wwiv/deps/my_basic-master/core/my_basic.c: In function ‘_core_div’:
/home/drock/git/wwiv/deps/my_basic-master/core/my_basic.c:12990:2: warning: large integer implicitly truncated to unsigned type [-Woverflow]
  _proc_div_by_zero(s, l, _exit, result, SE_RN_DIVIDE_BY_ZERO);
  ^
/home/drock/git/wwiv/deps/my_basic-master/core/my_basic.c:12990:2: warning: large integer implicitly truncated to unsigned type [-Woverflow]
/home/drock/git/wwiv/deps/my_basic-master/core/my_basic.c:12990:2: warning: large integer implicitly truncated to unsigned type [-Woverflow]
/home/drock/git/wwiv/deps/my_basic-master/core/my_basic.c:12990:2: warning: large integer implicitly truncated to unsigned type [-Woverflow]
/home/drock/git/wwiv/deps/my_basic-master/core/my_basic.c: In function ‘_core_mod’:
/home/drock/git/wwiv/deps/my_basic-master/core/my_basic.c:13003:2: warning: large integer implicitly truncated to unsigned type [-Woverflow]
  _proc_div_by_zero(s, l, _exit, result, SE_RN_MOD_BY_ZERO);
  ^
/home/drock/git/wwiv/deps/my_basic-master/core/my_basic.c:13003:2: warning: large integer implicitly truncated to unsigned type [-Woverflow]
/home/drock/git/wwiv/deps/my_basic-master/core/my_basic.c:13003:2: warning: large integer implicitly truncated to unsigned type [-Woverflow]
/home/drock/git/wwiv/deps/my_basic-master/core/my_basic.c:13003:2: warning: large integer implicitly truncated to unsigned type [-Woverflow]

```

**Comment by wwiv** [comment]
what do I need to install on centos7 to compile wwiv?

**Comment by granitepenguin** [comment]
Software Collections 

```bash
yum install centos-release-scl-rh
yum install devtoolset-3-gcc devtoolset-3-gcc-c++
scl enable devtoolset-3 bash
```

This will install 4.9.2 in something similar to a chroot env that you can access with the ``scl`` command.  You can get more details about software collections at https://www.softwarecollections.org/en/

**Comment by wwiv** [comment]
I believe most of these are fixed now (also aren't specific to centos, but all gcc 4.9x)

**Comment by granitepenguin** [comment]
yup, compiles cleanly for me now.  Still have the floating point issue running bbs, though ( #981 )
